[package]
name = "hstr-leak"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.34.3"
swc_ecma_ast = "0.115.1"
swc_ecma_parser = "0.146.8"
swc_ecma_transforms_base = "0.140.1"
swc_ecma_visit = "0.101.0"
